### ISSUE TITLE
Determine what to do with unmatched nuclei & cells

### ISSUE THREAD

**Issue by dchaley** [dchaley/qupath-project-initializer#47]
User question: what do we do with nuclei that don't have whole-cell matches, as well as whole-cells that don't have nucleus matches?

We only match nuclei & cells that overlap at least 1 pixel. (Maybe we should only keep >50% overlaps but that's another story.)

This means that nucleus & cell detections without any corresponding overlap won't match. Currently we just discard these.

Should we keep them, as generic detection objects? (vs detected cells w/ 2 compartments)

**Comment by dchaley** [comment]
cc @bnovotny  do you have any thoughts on this? (Please see above question)

Welcome back by the way 😁

**Comment by bnovotny** [comment]
Thanks a lot, it's good to be back!

This is actually very timely because I was just dealing with cell compartments in QuPath this morning! I'm leaning towards keeping them as generic detection objects. 

We found that if we run the compartment-specific marker quantification on detection objects with no nucleus, the "nucleus" meaurements become NaN and the "cytoplasm" and "cell" measurements just become identical. Therefore it would be easy to filter out detections with no nucleus in the downstream analysis if necessary (assuming the quantification works as we expect).

**Comment by dchaley** [comment]
Thanks Brenna! We just merged the code to keep whole-cell compartments that don't match to nuclei.

How about the nuclei that don't match to cells: do you want to keep those, or discard them?

**Comment by bnovotny** [comment]
Awesome! I'd say discard the nuclei that don't match cells, I don't think there's much we could do with them. Thank you!!

**Comment by dchaley** [comment]
Awesome, thank you! Then I'll close out this issue 😁
